# Copyright 2017-2021, Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:jammy
ENV LINUXDISTRO=jammy

ARG CLEAN_BUILD_COUNTER=5
ENV CLEAN_BUILD_COUNTER=${CLEAN_BUILD_COUNTER}

RUN apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
        make cmake gcc gdb strace valgrind uuid-dev \
        curl vim cpio zip unzip doxygen sudo patchelf

RUN for pp in python3.10 python3.11; do \
        DEBIAN_FRONTEND=noninteractive apt-get -y install \
            ${pp}-dev ${pp}-venv python3-pip python3-setuptools; \
        ${pp} -m pip install wheel numpy cython; \
    done

RUN apt-get -y install clang libomp-dev lld && \
      echo "c++ manual /usr/bin/clang++" | update-alternatives --set-selections

RUN useradd -m -u 800 -G sudo --shell /bin/bash -p '' me
USER me
WORKDIR /home/me

# SOURCE CODE FROM BUILD CONTEXT COPIED IN
COPY --chown=800 ./ oz/
WORKDIR /home/me/oz
