# Copyright 2017-2020, Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:focal

RUN apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
        make cmake gcc gdb strace valgrind \
        uuid-dev libssl-dev libcurl4-openssl-dev \
        curl vim cpio zip unzip doxygen sudo \
        python3-dev python3-pip python3-setuptools python3-tk \
        graphviz

# Add ~300 packages to allow Doxygen to generate a single-file refman.pdf
RUN apt-get update; \
    apt-get -y install pdftk texlive \
        texlive-font-utils texlive-latex-extra

RUN pip3 install wheel numpy cython

RUN useradd -u 800 -g users me; \
    echo 'me ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers

WORKDIR /home/me/oz
COPY ./ ./

RUN chown -R me /home/me
USER me

### Usage example:
#
# docker build --pull -t oz -f scripts/Dockerfile-doc .
# docker run --rm -it oz
