# Copyright 2017-2021, Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG variant=cloud

#############################################################################
###   SDAPI build prerequisites   ###########################################
#############################################################################

FROM ubuntu:jammy AS sdapi-base
ENV LINUXDISTRO=jammy

ARG CLEAN_BUILD_COUNTER=5
ENV CLEAN_BUILD_COUNTER=${CLEAN_BUILD_COUNTER}

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
        g++ cmake curl libcurl4-openssl-dev libssl-dev zip \
	      git vim sudo pkg-config cpio patchelf \
        ca-certificates
RUN useradd -m -u 800 -G sudo --shell /bin/bash -p '' me
WORKDIR /home/me

COPY ["sd-env/.empty", "private/Slb*.crt", "/usr/local/share/ca-certificates/"]
RUN update-ca-certificates

#############################################################################
###   SDAPI third party dependencies (have patience)   ######################
#############################################################################

FROM sdapi-base AS sdapi-manual
#ARG vcpkg_branch=52b66042
# 8-12-2023
#ARG  vcpkg_branch=8ee46dc7
# 6-8-2024
#ARG  vcpkg_branch=a2367cee
# 2-1-2025
ARG vcpkg_branch=4b6c50d9

RUN mkdir -p /opt/vcpkg && chown me /opt/vcpkg
USER me
RUN git clone https://github.com/microsoft/vcpkg.git /opt/vcpkg && \
    cd /opt/vcpkg && git checkout ${vcpkg_branch} && \
    git rev-parse HEAD && \
    cd /opt/vcpkg && ./bootstrap-vcpkg.sh -disableMetrics
RUN cd /opt/vcpkg; ./vcpkg install azure-storage-cpp:x64-linux
RUN cd /opt/vcpkg; ./vcpkg install azure-storage-blobs-cpp:x64-linux

# The following is for when vcpkg builds dynamic objects.
# Currently it builds static libraries, which has very different issues.
#
# On CentOS and derivatives:
#
# Locally built and system libcurl are compatible. But they cannot co-exist in
# the same executable because the symbols partly overlap. This means that all
# references to libcurl must use the same SONAME. vcpkg uses a different name
# when building, libcurl.so instead of libcurl.so.4 like the system does. The
# SONAME for the locally built libcurl and any reference to it needs to be
# patched. Initially, ZgyTool will find the locally built version. If the
# system version turns out to be newer then the end user can simply remove the
# locally built version. Which will cause the system one to get picked up.
#
# On Debian and derivatives:
#
# Locally built and system libcurl are incompatible. Because vcpkg builds
# without versioned symbols while the system library does use them. This means
# that the two libraries should be able to co-exist. And in this case the
# SONAME needs to be different. It currently is. If this changes then the
# name will need to be patched here.
#
# The locally built libcurl uses a newer ssl (libssl.so.3 and libcrypto.so.3)
# but those don't have overlapping symbols. So we should be good. And on that
# topic, the nss system package installs libssl3.so which appears to be
# something completely different than libssl.so.3 Ignore that one.
#
#COPY ["scripts/sofixup", "/tmp/sofixup"]
#RUN find /opt/vcpkg/installed -name 'lib*.so*' -type f ! -name \*boost\* -print0 | xargs -r0 readelf -d
#RUN find /opt/vcpkg/installed -name 'lib*.so*' -type f -print0 | xargs -r0 ls -ld
#RUN set -e; cd /opt/vcpkg/installed/x64-linux/lib; \
#    test -h libcurl.so || mv -f libcurl.so libcurl.so.vcpkg; \
#    /tmp/sofixup -l libcurl.so libcurl.so.4 lib*.so*; \
#    cd /opt/vcpkg/installed/x64-linux/debug/lib; \
#    test -h libcurl-d.so || mv -f libcurl-d.so libcurl-d.so.vcpkg; \
#    /tmp/sofixup -l libcurl-d.so libcurl-d.so.4 lib*.so*

#############################################################################
###   Environment is ready, build SDAPI now!   ##############################
#############################################################################

FROM sdapi-manual AS sdapi-build

# SOURCE CODE FROM BUILD CONTEXT COPIED IN
COPY --chown=800 seismic-store-cpp-lib /home/me/sdapi/
COPY --chown=800 ["sd-env/build-template.sh", "sd-env/*.patch", "/home/me/" ]
USER me

ARG AZURE_BUILDID
ENV AZURE_BUILDID=${AZURE_BUILDID}
RUN ./build-template.sh

# If stopping the build at this point, /home/me/sdapi_linux64.tar.gz
# can be extracted from the image and deployed e.g. as a universal package.
